import type { Metadata } from 'next';

import './global.css';

export const metadata: Metadata = {
  title: '农历纪念日订阅',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
